### ISSUE TITLE
Regarding Training

### ISSUE THREAD

**Issue by slbinilkumar** [ryanleary/patter#6]
Hi,
While training 
1. where we had mention the labels
2. How to add the manifest files

**Comment by ryanleary** [comment]
Hey -- I will be adding more documentation in the coming weeks as things solidify. You need three files for training: a corpus configuration, a training configuration, and a model configuration. You can find the details of what you can configure from the files in `patter/config`, but below are some samples that set up a similar model and training environment as [SeanNaren/deepspeech.pytorch](https://github.com/seannaren/deepspeech).

`corpus_config.toml`:
```toml
min_duration = 1.0
max_duration = 17.0


[[dataset]]
name = "train"
manifest = "/path/to/corpora/libritrain.json"
augment = true

[[dataset]]
name = "val"
manifest = "/path/to/corpora/val.json"
augment = false


[[augmentation]]
type = "noise"
prob = 0.0
[augmentation.config]
manifest = "/Users/ryanleary/devel/snc/patter_data/noise_manifest.json"
min_snr_db = 3
max_snr_db = 35

[[augmentation]]
type = "impulse"
prob = 0.0
[augmentation.config]
manifest = "/Users/ryanleary/devel/snc/patter_data/impulse_manifest.json"

[[augmentation]]
type = "speed"
prob = 1.0
[augmentation.config]
min_speed_rate = 0.95
max_speed_rate = 1.05

[[augmentation]]
type = "shift"
prob = 1.0
[augmentation.config]
min_shift_ms = -5
max_shift_ms = 5

[[augmentation]]
type = "gain"
prob = 1.0
[augmentation.config]
min_gain_dbfs = -10
max_gain_dbfs = 10
```

`model_config.toml`
```toml
model = "DeepSpeechOptim"

[input]
type = "stft"
normalize = true
sample_rate = 16000
window_size = 0.02
window_stride = 0.01
window = "hamming"

[[cnn]]
filters = 32
kernel = [41, 11]
stride = [2, 2]
padding = [0, 10]
batch_norm = true
activation = "hardtanh"
activation_params = [0, 20]

[[cnn]]
filters = 32
kernel = [21, 11]
stride = [2, 1]
padding = [0, 2]
batch_norm = true
activation = "hardtanh"
activation_params = [0, 20]

[rnn]
type = "lstm"
bidirectional = true
size = 512
layers = 4
batch_norm = true

[labels]
labels = [
  "'", "A", "B", "C", "D", "E", "F", "G", "H",
  "I", "J", "K", "L", "M", "N", "O", "P", "Q",
  "R", "S", "T", "U", "V", "W", "X", "Y", "Z", " ",
]
```

`training_config.toml`:
```toml
id = "expt-name"
cuda = true

[output]
model_path = "/path/to/best/model.pt"
log_path = "/path/to/tensorboard/logs"

[trainer]
epochs = 20
batch_size = 32
num_workers = 4
max_norm = 400

[trainer.optimizer]
optimizer = "sgd"
lr = 3e-4
momentum = 0.9
anneal = 0.85
```
